# site name
siteName: 李坤&个人博客
shortName: 文


# full https model which means #Content-Security-Policy = upgrade-insecure-requests# in meat tag
fullHttps: false

# favicon
favicon: /images/favicon.png
# unique avatar
avatarShow: false
avatarImage: /images/favicon.png

# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10


# your site build time or domain buy time
siteBuildingTime: 01/20/2018


# Top navigate menu name
## Notice:
## Name order decide show index.The name also called category alias,so you must set category alias before start server.
## BTW,'category_map' and 'tag_map' field in site '_config.yml' file must one to one correspondence with menus below.
menu:
  前端: front
  后台: server
  大数据: big-data
  其他: other
  资源: resource

# Left menu of single pages settings
## Notice: faName is FontAwesome style name
leftPagesMenu:
- uri: help
  title: 帮助
  faName: fa-question-circle
- uri: other
  title: 其他
  faName: fa-desktop


# cover info config
coverTitle: 在不知足中前行
coverDescription: 我们热爱这个世界时，才真正活在这个世界上

# sns url
sns:
  facebook-square: http://www.baidu.com
  github: https://github.com/gitHber

# your article copyright or content declare
postDeclare: 本文代表个人观点，内容仅供参考。若有不恰当之处，望不吝赐教！

# Git-pages server info
pageServerName: Coding
pageServerUrl: https://coding.net/register?key=H5UX0I


# Gitment
# Introduction: https://imsun.net/posts/gitment-introduction/
gitment:
  enable: true
  githubID: gitHber
  repo: githber-comments
  ClientID: 0e03c79c74d359332c6d
  ClientSecret: 8d412d0b0fa2be9f78dca756e16a0c69331a0e6e
  lazy: false

## Comments settings.You can choose only ONE to display.
# disqus shortName,
disqus_shortname:

# Analytics
tentcentAnalyticsId: 65725085
